-- Flavor wheel. Groups are the outer ring; slugs the inner ring.
insert into public.flavor_tags (slug, label, group_slug, group_label, sort) values
  -- Fruit
  ('apple',        'Apple',          'fruit',  'Fruit',        10),
  ('pear',         'Pear',           'fruit',  'Fruit',        11),
  ('citrus',       'Citrus',         'fruit',  'Fruit',        12),
  ('orange_peel',  'Orange peel',    'fruit',  'Fruit',        13),
  ('stone_fruit',  'Stone fruit',    'fruit',  'Fruit',        14),
  ('cherry',       'Cherry',         'fruit',  'Fruit',        15),
  ('red_berries',  'Red berries',    'fruit',  'Fruit',        16),
  ('dark_fruit',   'Dark fruit',     'fruit',  'Fruit',        17),
  ('raisin',       'Raisin / fig',   'fruit',  'Fruit',        18),
  ('tropical',     'Tropical',       'fruit',  'Fruit',        19),
  ('banana',       'Banana',         'fruit',  'Fruit',        20),
  -- Floral / herbal
  ('floral',       'Floral',         'floral', 'Floral & herbal', 30),
  ('heather',      'Heather',        'floral', 'Floral & herbal', 31),
  ('grassy',       'Grassy',         'floral', 'Floral & herbal', 32),
  ('mint',         'Mint',           'floral', 'Floral & herbal', 33),
  ('herbal',       'Herbal',         'floral', 'Floral & herbal', 34),
  ('tea',          'Tea',            'floral', 'Floral & herbal', 35),
  -- Sweet
  ('vanilla',      'Vanilla',        'sweet',  'Sweet',        40),
  ('caramel',      'Caramel',        'sweet',  'Sweet',        41),
  ('toffee',       'Toffee',         'sweet',  'Sweet',        42),
  ('honey',        'Honey',          'sweet',  'Sweet',        43),
  ('maple',        'Maple',          'sweet',  'Sweet',        44),
  ('brown_sugar',  'Brown sugar',    'sweet',  'Sweet',        45),
  ('chocolate',    'Chocolate',      'sweet',  'Sweet',        46),
  ('butterscotch', 'Butterscotch',   'sweet',  'Sweet',        47),
  ('marzipan',     'Marzipan',       'sweet',  'Sweet',        48),
  -- Spice
  ('cinnamon',     'Cinnamon',       'spice',  'Spice',        50),
  ('clove',        'Clove',          'spice',  'Spice',        51),
  ('nutmeg',       'Nutmeg',         'spice',  'Spice',        52),
  ('black_pepper', 'Black pepper',   'spice',  'Spice',        53),
  ('ginger',       'Ginger',         'spice',  'Spice',        54),
  ('anise',        'Anise / licorice','spice', 'Spice',        55),
  ('baking_spice', 'Baking spice',   'spice',  'Spice',        56),
  ('rye_spice',    'Rye spice',      'spice',  'Spice',        57),
  -- Wood
  ('oak',          'Oak',            'wood',   'Wood',         60),
  ('char',         'Char',           'wood',   'Wood',         61),
  ('cedar',        'Cedar',          'wood',   'Wood',         62),
  ('tobacco',      'Tobacco',        'wood',   'Wood',         63),
  ('leather',      'Leather',        'wood',   'Wood',         64),
  ('sherry',       'Sherry',         'wood',   'Wood',         65),
  ('port',         'Port',           'wood',   'Wood',         66),
  ('tannic',       'Tannic',         'wood',   'Wood',         67),
  -- Grain / nutty
  ('cereal',       'Cereal',         'grain',  'Grain & nut',  70),
  ('malt',         'Malt',           'grain',  'Grain & nut',  71),
  ('corn',         'Sweet corn',     'grain',  'Grain & nut',  72),
  ('bread',        'Bread / pastry', 'grain',  'Grain & nut',  73),
  ('almond',       'Almond',         'grain',  'Grain & nut',  74),
  ('walnut',       'Walnut',         'grain',  'Grain & nut',  75),
  ('hazelnut',     'Hazelnut',       'grain',  'Grain & nut',  76),
  ('coffee',       'Coffee',         'grain',  'Grain & nut',  77),
  -- Smoke / peat / earth
  ('peat',         'Peat',           'smoke',  'Smoke & earth', 80),
  ('smoke',        'Smoke',          'smoke',  'Smoke & earth', 81),
  ('bonfire',      'Bonfire',        'smoke',  'Smoke & earth', 82),
  ('medicinal',    'Medicinal',      'smoke',  'Smoke & earth', 83),
  ('brine',        'Brine / sea',    'smoke',  'Smoke & earth', 84),
  ('iodine',       'Iodine',         'smoke',  'Smoke & earth', 85),
  ('earthy',       'Earthy',         'smoke',  'Smoke & earth', 86),
  ('rubber',       'Rubber',         'smoke',  'Smoke & earth', 87),
  -- Texture / other
  ('creamy',       'Creamy',         'other',  'Texture & other', 90),
  ('oily',         'Oily',           'other',  'Texture & other', 91),
  ('thin',         'Thin',           'other',  'Texture & other', 92),
  ('hot',          'Hot / ethanol',  'other',  'Texture & other', 93),
  ('sulfur',       'Sulfur',         'other',  'Texture & other', 94),
  ('funky',        'Funky',          'other',  'Texture & other', 95),
  ('dry',          'Dry',            'other',  'Texture & other', 96),
  ('long_finish',  'Long finish',    'other',  'Texture & other', 97)
on conflict (slug) do nothing;
